name: lipl_bluetooth
description: Scan for TV devices and write a part to them
repository: https://github.com/paulusminus/lipl-control/
publish_to: "none"

version: 1.13.18

environment:
  sdk: ^3.9.2
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^9.0.0
  flutter_blue_plus: ^2.0.0
  logging: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.0.0
  build_runner: ^2.4.6

flutter:
  generate: true
  uses-material-design: true
