name: lipl_model
description: Domain models for lipl.
repository: https://github.com/paulusminus/lipl-control/
version: 1.13.19
publish: false

environment:
  sdk: ^3.10.1
resolution: workspace

dependencies:
  bs58: ^1.0.2
  collection: ^1.19.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^3.0.0
  lints: ^6.0.0
  json_serializable: ^6.9.4
  test: ^1.24.9
